# Site settings
title: Stitch Fix Technology – Multithreaded
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Stitch Fix is a full-stack startup creating unique solutions in
  data-driven merchandising, massively scaled personal styling, and
  complex logistics.
baseurl: ""
url: "http://technology.stitchfix.com/"
production_url: "http://technology.stitchfix.com"
twitter_username: stitchfix
github_username:  stitchfix
atom_path: "atom.xml"

collections:
  jobs:
    output: true
    permalink: /jobs/:path/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

category_dir: "blog"

# Owner (organization or individual) of site content
author: "Stitch Fix"
url: "http://technology.stitchfix.com/"

# Pagination variable for how many posts to show in a list
paginate: 10
paginate_path: "/blog/page/:num/"

# Style of permalinks
permalink: /blog/:year/:month/:day/:title

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

exclude: [Rakefile, README.md, old, Gemfile, Gemfile.lock]

markdown: redcarpet
redcarpet:
  extensions: ["tables"]
